# Staging Environment Configuration
app:
  title: Arcadia Developer Portal (Staging)
  baseUrl: https://arcadia-dev-2af84.web.app

backend:
  baseUrl: https://backstage-backend--arcadia-dev-2af84.us-central1.hosted.app
  listen:
    port: ${PORT:8080}
    host: 0.0.0.0
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
  cors:
    origin: https://arcadia-dev-2af84.web.app
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      ssl: 
        rejectUnauthorized: false

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

auth:
  providers:
    google:
      staging:
        clientId: ${GOOGLE_CLIENT_ID}
        clientSecret: ${GOOGLE_CLIENT_SECRET}